/* Generated By:JJTree: Do not edit this line. ASTAtribuicao.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package compiler;

public class ASTAtribuicao extends SimpleNode {
  public ASTAtribuicao(int id) {
    super(id);
  }

  public ASTAtribuicao(ParaCompiler p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParaCompilerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2caf5b87d8959dd13eea637f5af7ca2d (do not edit this line) */
