/* Generated By:JJTree: Do not edit this line. ASTAtribuicao.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTAtribuicao extends SimpleNode {
  public ASTAtribuicao(int id) {
    super(id);
  }

  public ASTAtribuicao(ParaCompiler p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParaCompilerVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=00719a1f84b943da5dcbe787dcde57bc (do not edit this line) */
