/* Generated By:JJTree: Do not edit this line. ASTDeclaracao.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package compiler;

public class ASTDeclaracao extends SimpleNode {
  public ASTDeclaracao(int id) {
    super(id);
  }

  public ASTDeclaracao(ParaCompiler p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParaCompilerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9e0b402094a0f5cd06ae3fce03af4e61 (do not edit this line) */
