/* Generated By:JJTree: Do not edit this line. ASTDeclaracao.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTDeclaracao extends SimpleNode {
  public ASTDeclaracao(int id) {
    super(id);
  }

  public ASTDeclaracao(ParaCompiler p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParaCompilerVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=77e498bd42c2a856335a73711d3adbcf (do not edit this line) */
