/* Generated By:JJTree: Do not edit this line. ASTExpLogica.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package compiler;

public class ASTExpLogica extends SimpleNode {
  public ASTExpLogica(int id) {
    super(id);
  }

  public ASTExpLogica(ParaCompiler p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParaCompilerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=add25f96d8c18be6ffa8c2b88788e86f (do not edit this line) */
