/* Generated By:JJTree: Do not edit this line. ASTExpLogica.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTExpLogica extends SimpleNode {
  public ASTExpLogica(int id) {
    super(id);
  }

  public ASTExpLogica(ParaCompiler p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParaCompilerVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6848dd978fb72b5b7bd1ddbf3e72527c (do not edit this line) */
