/* Generated By:JJTree: Do not edit this line. ASTFactor.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package compiler;

public class ASTFactor extends SimpleNode {
  public ASTFactor(int id) {
    super(id);
  }

  public ASTFactor(ParaCompiler p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParaCompilerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=58dc65ddf8eedc11199bbe0fc90935ad (do not edit this line) */
