/* Generated By:JJTree: Do not edit this line. ASTForInc.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package compiler;

public class ASTForInc extends SimpleNode {
  public ASTForInc(int id) {
    super(id);
  }

  public ASTForInc(ParaCompiler p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParaCompilerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c3bd8a94eb1f0600bea17f74c9814134 (do not edit this line) */
