/* Generated By:JJTree: Do not edit this line. ASTIdent.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package compiler;

public class ASTIdent extends SimpleNode {
  public ASTIdent(int id) {
    super(id);
  }

  public ASTIdent(ParaCompiler p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParaCompilerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6003aeacfb738a84480ffc6f65f90da7 (do not edit this line) */
