/* Generated By:JJTree: Do not edit this line. ASTListaId.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package compiler;

public class ASTListaId extends SimpleNode {
  public ASTListaId(int id) {
    super(id);
  }

  public ASTListaId(ParaCompiler p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParaCompilerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=90e0f6979375f60c9d1fb355b4ea4e91 (do not edit this line) */
