/* Generated By:JJTree: Do not edit this line. ASTOpLog.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTOpLog extends SimpleNode {
  public ASTOpLog(int id) {
    super(id);
  }

  public ASTOpLog(ParaCompiler p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParaCompilerVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6527a14ec5e6088db781083afacc9c67 (do not edit this line) */
