/* Generated By:JJTree: Do not edit this line. ASTOpLog.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package compiler;

public class ASTOpLog extends SimpleNode {
  public ASTOpLog(int id) {
    super(id);
  }

  public ASTOpLog(ParaCompiler p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParaCompilerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3ab3e9f15d4d8a2ad72fcdba471b99c2 (do not edit this line) */
