/* Generated By:JJTree: Do not edit this line. ASTtipoDado.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package compiler;

public class ASTtipoDado extends SimpleNode {
  public ASTtipoDado(int id) {
    super(id);
  }

  public ASTtipoDado(ParaCompiler p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParaCompilerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8fa5b1207040384e582cdd14fa10c3df (do not edit this line) */
