/* Generated By:JJTree: Do not edit this line. ASTtipoDado.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compiler;

public
class ASTtipoDado extends SimpleNode {
  public ASTtipoDado(int id) {
    super(id);
  }

  public ASTtipoDado(ParaCompiler p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParaCompilerVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=62dd26a14037d68e92db03a3e1998ad8 (do not edit this line) */
