/* Generated By:JavaCC: Do not edit this line. ParaCompilerTreeConstants.java Version 7.0.12 */
package compiler;

public interface ParaCompilerTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSTATEMENT = 1;
  public int JJTATRIBUICAO = 2;
  public int JJTDECLARACAO = 3;
  public int JJTTIPODADO = 4;
  public int JJTIDENT = 5;
  public int JJTLISTAID = 6;
  public int JJTEXPRESSION = 7;
  public int JJTTERM = 8;
  public int JJTFACTOR = 9;
  public int JJTOPLOG = 10;
  public int JJTEXPLOGICA = 11;
  public int JJTIF = 12;
  public int JJTWHILE = 13;
  public int JJTFORINC = 14;
  public int JJTFOR = 15;


  public String[] jjtNodeName = {
    "Program",
    "Statement",
    "Atribuicao",
    "Declaracao",
    "tipoDado",
    "Ident",
    "ListaId",
    "Expression",
    "Term",
    "Factor",
    "OpLog",
    "ExpLogica",
    "If",
    "While",
    "ForInc",
    "For",
  };
}
/* JavaCC - OriginalChecksum=86e52944b3606404dcb36142d6a8ae5e (do not edit this line) */
