/* Generated By:JavaCC: Do not edit this line. ParaCompilerConstants.java */
package compiler;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParaCompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIOPROG = 6;
  /** RegularExpression Id. */
  int ABREBLOCO = 7;
  /** RegularExpression Id. */
  int FECHABLOCO = 8;
  /** RegularExpression Id. */
  int FIMINSTRUC = 9;
  /** RegularExpression Id. */
  int INICIAVAR = 10;
  /** RegularExpression Id. */
  int FOR = 11;
  /** RegularExpression Id. */
  int WHILE = 12;
  /** RegularExpression Id. */
  int IF = 13;
  /** RegularExpression Id. */
  int ELSE = 14;
  /** RegularExpression Id. */
  int ATRIBUICAO = 15;
  /** RegularExpression Id. */
  int TIPOCHAR = 16;
  /** RegularExpression Id. */
  int TIPOINT = 17;
  /** RegularExpression Id. */
  int TIPOFLOAT = 18;
  /** RegularExpression Id. */
  int OPMAIOR = 19;
  /** RegularExpression Id. */
  int OPMENOR = 20;
  /** RegularExpression Id. */
  int OPDIF = 21;
  /** RegularExpression Id. */
  int OPIGUAL = 22;
  /** RegularExpression Id. */
  int OPINC = 23;
  /** RegularExpression Id. */
  int OPDEC = 24;
  /** RegularExpression Id. */
  int ABREPARENT = 25;
  /** RegularExpression Id. */
  int FECHAPARENT = 26;
  /** RegularExpression Id. */
  int VIRGULA = 27;
  /** RegularExpression Id. */
  int PLUS = 28;
  /** RegularExpression Id. */
  int MINUS = 29;
  /** RegularExpression Id. */
  int TIMES = 30;
  /** RegularExpression Id. */
  int DIVIDE = 31;
  /** RegularExpression Id. */
  int IDENT = 32;
  /** RegularExpression Id. */
  int NUM = 33;
  /** RegularExpression Id. */
  int STRING_LITERAL = 34;
  /** RegularExpression Id. */
  int DIGITO = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\u00a0\"",
    "\"ohjata\"",
    "\"<\"",
    "\">\"",
    "\".\"",
    "\"disk\"",
    "\"dalhe\"",
    "\"caquiado\"",
    "\"emesmo\"",
    "\"masquando\"",
    "\"->\"",
    "\"egua\"",
    "\"intera\"",
    "\"meroubalogo\"",
    "\">>\"",
    "\"<<\"",
    "\"!=\"",
    "\"==\"",
    "\"++\"",
    "\"--\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<IDENT>",
    "<NUM>",
    "<STRING_LITERAL>",
    "<DIGITO>",
  };

}
