/* ParaCompiler.java */
/* Generated By:JJTree&JavaCC: Do not edit this line. ParaCompiler.java */
package compiler;

import java.util.*;
import java.io.*;

public class ParaCompiler/* @bgen(jjtree) */ implements ParaCompilerTreeConstants, ParaCompilerConstants {/*
                                                                                                           * @bgen(
                                                                                                           * jjtree)
                                                                                                           */
  protected JJTParaCompilerState jjtree = new JJTParaCompilerState();
  // Lista de erros e tokens
  public static List<String> errors = new ArrayList<String>();
  public static List<String> tokens = new ArrayList<String>();

  public static void addToken(String token) {
    tokens.add(token);
  }

  public static void addError(String msg, int line, int col) {
    errors.add(String.format("Linha %d, Col %d: %s", line, col, msg));
  }

  // SINCRONIZAÇÃO DE PÂNICO
  void recover(ParseException e, int... syncTokens) throws ParseException {
    addError("CAVALO MORDEU TUA CABE\u00c7A? " + e.getMessage(),
        e.currentToken.beginLine,
        e.currentToken.beginColumn);

    Token t;
    do {
      t = getNextToken();
    } while (!isSync(t.kind, syncTokens) && t.kind != EOF);
  }

  boolean isSync(int kind, int[] sync) {
    for (int s : sync)
      if (kind == s)
        return true;
    return false;
  }

  public static void main(String args[]) throws Exception {
    ParaCompiler parser;
    if (args.length == 0) {
      parser = new ParaCompiler(System.in);
    } else {
      parser = new ParaCompiler(new FileInputStream(args[0]));
    }

    errors.clear();
    tokens.clear();

    try {
      SimpleNode root = parser.program();

      System.out.println("\n========================================");
      System.out.println("   RESULTADO DA COMPILA\u00c7\u00c3O");
      System.out.println("========================================\n");

      if (errors.isEmpty()) {
        System.out.println("\u2705 C\u00d3DIGO ACEITO! T\u00e1 massa, bich\u00e3o!\n");
      } else {
        System.out.println("\u274c C\u00d3DIGO REJEITADO! Tu \u00e9 leso!\n");
        System.out.println("ERROS ENCONTRADOS:");
        for (String e : errors) {
          System.out.println("  \u2022 " + e);
        }
        System.out.println();
      }

      System.out.println("TOKENS RECONHECIDOS:");
      System.out.println("  " + String.join(" ", tokens));

      System.out.println("\n========================================");
      System.out.println("   \u00c1RVORE SINT\u00c1TICA ABSTRATA");
      System.out.println("========================================\n");
      root.dump("  ");

      // Se flag --json foi passada, gerar saída JSON para visualização
      if (args.length > 1 && args[1].equals("--json")) {
        System.out.println("\n========================================");
        System.out.println("   JSON DA ÁRVORE (para Electron)");
        System.out.println("========================================\n");
        System.out.println(root.toJSON());
      }

    } catch (Exception e) {
      System.out.println("\u274c ERRO FATAL: " + e.getMessage());
      e.printStackTrace();
    }
  }

  // ============================================
  // REGRAS GRAMATICAIS COM ANOTAÇÃO DE ÁRVORE
  // ============================================

  // #NomeDoNo cria um nó na árvore
  final public SimpleNode program() throws ParseException {/* @bgen(jjtree) Program */
    ASTProgram jjtn000 = new ASTProgram(JJTPROGRAM);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);
    try {
      try {
        jj_consume_token(INICIOPROG);
        jj_consume_token(ABREBLOCO);
        label_1: while (true) {
          if (jj_2_1(2)) {
            ;
          } else {
            break label_1;
          }
          statement();
        }
        jj_consume_token(FECHABLOCO);
        jj_consume_token(0);
        {
          if ("" != null)
            return jjtn000;
        }
      } catch (ParseException e) {
        recover(e, FECHABLOCO, EOF);
        {
          {
            if ("" != null)
              return jjtn000;
          }
        }
      }
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {
          if (true)
            throw (RuntimeException) jjte000;
        }
      }
      if (jjte000 instanceof ParseException) {
        {
          if (true)
            throw (ParseException) jjte000;
        }
      }
      {
        if (true)
          throw (Error) jjte000;
      }
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public void statement() throws ParseException {/* @bgen(jjtree) Statement */
    ASTStatement jjtn000 = new ASTStatement(JJTSTATEMENT);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);
    try {
      try {
        if (jj_2_5(2)) {
          if (jj_2_2(2)) {
            declaracao();
          } else if (jj_2_3(2)) {
            atribuicao();
          } else if (jj_2_4(2)) {
            expression();
          } else {
            jj_consume_token(-1);
            throw new ParseException();
          }
          jj_consume_token(FIMINSTRUC);
        } else if (jj_2_6(2)) {
          ifStatement();
        } else if (jj_2_7(2)) {
          whileStatement();
        } else if (jj_2_8(2)) {
          forStatement();
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (ParseException e) {
        recover(e, FIMINSTRUC, FECHABLOCO);
      }
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {
          if (true)
            throw (RuntimeException) jjte000;
        }
      }
      if (jjte000 instanceof ParseException) {
        {
          if (true)
            throw (ParseException) jjte000;
        }
      }
      {
        if (true)
          throw (Error) jjte000;
      }
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void atribuicao() throws ParseException {/* @bgen(jjtree) Atribuicao */
    ASTAtribuicao jjtn000 = new ASTAtribuicao(JJTATRIBUICAO);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);
    Token id;
    try {
      id = jj_consume_token(IDENT);
      jjtn000.jjtSetValue(id.image);
      jj_consume_token(ATRIBUICAO);
      expression();
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {
          if (true)
            throw (RuntimeException) jjte000;
        }
      }
      if (jjte000 instanceof ParseException) {
        {
          if (true)
            throw (ParseException) jjte000;
        }
      }
      {
        if (true)
          throw (Error) jjte000;
      }
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void declaracao() throws ParseException {/* @bgen(jjtree) Declaracao */
    ASTDeclaracao jjtn000 = new ASTDeclaracao(JJTDECLARACAO);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);
    Token tipo;
    try {
      jj_consume_token(INICIAVAR);
      tipo = tipoDado();
      jjtn000.jjtSetValue(tipo.image);
      listaIdentificadores();
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {
          if (true)
            throw (RuntimeException) jjte000;
        }
      }
      if (jjte000 instanceof ParseException) {
        {
          if (true)
            throw (ParseException) jjte000;
        }
      }
      {
        if (true)
          throw (Error) jjte000;
      }
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public Token tipoDado() throws ParseException {/* @bgen(jjtree) tipoDado */
    ASTtipoDado jjtn000 = new ASTtipoDado(JJTTIPODADO);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);
    Token t;
    try {
      if (jj_2_9(2)) {
        t = jj_consume_token(TIPOCHAR);
      } else if (jj_2_10(2)) {
        t = jj_consume_token(TIPOFLOAT);
      } else if (jj_2_11(2)) {
        t = jj_consume_token(TIPOINT);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
      {
        if ("" != null)
          return t;
      }
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public void identifier() throws ParseException {/* @bgen(jjtree) Ident */
    ASTIdent jjtn000 = new ASTIdent(JJTIDENT);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);
    Token t;
    try {
      t = jj_consume_token(IDENT);
      jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
      jjtn000.jjtSetValue(t.image);
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void listaIdentificadores() throws ParseException {/* @bgen(jjtree) ListaId */
    ASTListaId jjtn000 = new ASTListaId(JJTLISTAID);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);
    try {
      identifier();
      if (jj_2_12(2)) {
        jj_consume_token(ATRIBUICAO);
        expression();
      } else {
        ;
      }
      label_2: while (true) {
        if (jj_2_13(2)) {
          ;
        } else {
          break label_2;
        }
        jj_consume_token(VIRGULA);
        identifier();
        if (jj_2_14(2)) {
          jj_consume_token(ATRIBUICAO);
          expression();
        } else {
          ;
        }
      }
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {
          if (true)
            throw (RuntimeException) jjte000;
        }
      }
      if (jjte000 instanceof ParseException) {
        {
          if (true)
            throw (ParseException) jjte000;
        }
      }
      {
        if (true)
          throw (Error) jjte000;
      }
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void expression() throws ParseException {/* @bgen(jjtree) Expression */
    ASTExpression jjtn000 = new ASTExpression(JJTEXPRESSION);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);
    try {
      term();
      label_3: while (true) {
        if (jj_2_15(2)) {
          ;
        } else {
          break label_3;
        }
        if (jj_2_16(2)) {
          jj_consume_token(PLUS);
        } else if (jj_2_17(2)) {
          jj_consume_token(MINUS);
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
        term();
      }
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {
          if (true)
            throw (RuntimeException) jjte000;
        }
      }
      if (jjte000 instanceof ParseException) {
        {
          if (true)
            throw (ParseException) jjte000;
        }
      }
      {
        if (true)
          throw (Error) jjte000;
      }
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void term() throws ParseException {/* @bgen(jjtree) Term */
    ASTTerm jjtn000 = new ASTTerm(JJTTERM);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);
    try {
      factor();
      label_4: while (true) {
        if (jj_2_18(2)) {
          ;
        } else {
          break label_4;
        }
        if (jj_2_19(2)) {
          jj_consume_token(TIMES);
        } else if (jj_2_20(2)) {
          jj_consume_token(DIVIDE);
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
        factor();
      }
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {
          if (true)
            throw (RuntimeException) jjte000;
        }
      }
      if (jjte000 instanceof ParseException) {
        {
          if (true)
            throw (ParseException) jjte000;
        }
      }
      {
        if (true)
          throw (Error) jjte000;
      }
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void factor() throws ParseException {/* @bgen(jjtree) Factor */
    ASTFactor jjtn000 = new ASTFactor(JJTFACTOR);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);
    Token t;
    try {
      if (jj_2_21(2)) {
        t = jj_consume_token(NUM);
        jjtree.closeNodeScope(jjtn000, true);
        jjtc000 = false;
        jjtn000.jjtSetValue(t.image);
      } else if (jj_2_22(2)) {
        t = jj_consume_token(IDENT);
        jjtree.closeNodeScope(jjtn000, true);
        jjtc000 = false;
        jjtn000.jjtSetValue(t.image);
      } else if (jj_2_23(2)) {
        t = jj_consume_token(STRING_LITERAL);
        jjtree.closeNodeScope(jjtn000, true);
        jjtc000 = false;
        jjtn000.jjtSetValue(t.image);
      } else if (jj_2_24(2)) {
        jj_consume_token(ABREPARENT);
        expression();
        jj_consume_token(FECHAPARENT);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {
          if (true)
            throw (RuntimeException) jjte000;
        }
      }
      if (jjte000 instanceof ParseException) {
        {
          if (true)
            throw (ParseException) jjte000;
        }
      }
      {
        if (true)
          throw (Error) jjte000;
      }
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void opLog() throws ParseException {/* @bgen(jjtree) OpLog */
    ASTOpLog jjtn000 = new ASTOpLog(JJTOPLOG);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);
    Token t;
    try {
      if (jj_2_25(2)) {
        t = jj_consume_token(OPMAIOR);
      } else if (jj_2_26(2)) {
        t = jj_consume_token(OPMENOR);
      } else if (jj_2_27(2)) {
        t = jj_consume_token(OPDIF);
      } else if (jj_2_28(2)) {
        t = jj_consume_token(OPIGUAL);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
      jjtn000.jjtSetValue(t.image);
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void expLogica() throws ParseException {/* @bgen(jjtree) ExpLogica */
    ASTExpLogica jjtn000 = new ASTExpLogica(JJTEXPLOGICA);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);
    try {
      expression();
      opLog();
      expression();
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {
          if (true)
            throw (RuntimeException) jjte000;
        }
      }
      if (jjte000 instanceof ParseException) {
        {
          if (true)
            throw (ParseException) jjte000;
        }
      }
      {
        if (true)
          throw (Error) jjte000;
      }
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void ifStatement() throws ParseException {/* @bgen(jjtree) If */
    ASTIf jjtn000 = new ASTIf(JJTIF);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);
    try {
      try {
        jj_consume_token(IF);
        jj_consume_token(ABREPARENT);
        expLogica();
        jj_consume_token(FECHAPARENT);
        jj_consume_token(ABREBLOCO);
        label_5: while (true) {
          if (jj_2_29(2)) {
            ;
          } else {
            break label_5;
          }
          statement();
        }
        jj_consume_token(FECHABLOCO);
        if (jj_2_31(2)) {
          jj_consume_token(ELSE);
          jj_consume_token(ABREBLOCO);
          label_6: while (true) {
            if (jj_2_30(2)) {
              ;
            } else {
              break label_6;
            }
            statement();
          }
          jj_consume_token(FECHABLOCO);
        } else {
          ;
        }
      } catch (ParseException e) {
        recover(e, FECHABLOCO, FIMINSTRUC);
      }
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {
          if (true)
            throw (RuntimeException) jjte000;
        }
      }
      if (jjte000 instanceof ParseException) {
        {
          if (true)
            throw (ParseException) jjte000;
        }
      }
      {
        if (true)
          throw (Error) jjte000;
      }
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void whileStatement() throws ParseException {/* @bgen(jjtree) While */
    ASTWhile jjtn000 = new ASTWhile(JJTWHILE);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);
    try {
      try {
        jj_consume_token(WHILE);
        jj_consume_token(ABREPARENT);
        expLogica();
        jj_consume_token(FECHAPARENT);
        jj_consume_token(ABREBLOCO);
        label_7: while (true) {
          if (jj_2_32(2)) {
            ;
          } else {
            break label_7;
          }
          statement();
        }
        jj_consume_token(FECHABLOCO);
      } catch (ParseException e) {
        recover(e, FECHABLOCO, FIMINSTRUC);
      }
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {
          if (true)
            throw (RuntimeException) jjte000;
        }
      }
      if (jjte000 instanceof ParseException) {
        {
          if (true)
            throw (ParseException) jjte000;
        }
      }
      {
        if (true)
          throw (Error) jjte000;
      }
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void forIncremento() throws ParseException {/* @bgen(jjtree) ForInc */
    ASTForInc jjtn000 = new ASTForInc(JJTFORINC);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);
    Token id;
    try {
      id = jj_consume_token(IDENT);
      jjtn000.jjtSetValue(id.image);
      jj_consume_token(ATRIBUICAO);
      expression();
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {
          if (true)
            throw (RuntimeException) jjte000;
        }
      }
      if (jjte000 instanceof ParseException) {
        {
          if (true)
            throw (ParseException) jjte000;
        }
      }
      {
        if (true)
          throw (Error) jjte000;
      }
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void forStatement() throws ParseException {/* @bgen(jjtree) For */
    ASTFor jjtn000 = new ASTFor(JJTFOR);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);
    try {
      try {
        jj_consume_token(FOR);
        jj_consume_token(ABREPARENT);
        declaracao();
        expLogica();
        jj_consume_token(FIMINSTRUC);
        forIncremento();
        jj_consume_token(FECHAPARENT);
        jj_consume_token(ABREBLOCO);
        label_8: while (true) {
          if (jj_2_33(2)) {
            ;
          } else {
            break label_8;
          }
          statement();
        }
        jj_consume_token(FECHABLOCO);
      } catch (ParseException e) {
        recover(e, FECHABLOCO, FIMINSTRUC);
      }
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {
          if (true)
            throw (RuntimeException) jjte000;
        }
      }
      if (jjte000 instanceof ParseException) {
        {
          if (true)
            throw (ParseException) jjte000;
        }
      }
      {
        if (true)
          throw (Error) jjte000;
      }
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_1());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(0, xla);
    }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_2());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(1, xla);
    }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_3());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(2, xla);
    }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_4());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(3, xla);
    }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_5());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(4, xla);
    }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_6());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(5, xla);
    }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_7());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(6, xla);
    }
  }

  private boolean jj_2_8(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_8());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(7, xla);
    }
  }

  private boolean jj_2_9(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_9());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(8, xla);
    }
  }

  private boolean jj_2_10(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_10());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(9, xla);
    }
  }

  private boolean jj_2_11(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_11());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(10, xla);
    }
  }

  private boolean jj_2_12(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_12());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(11, xla);
    }
  }

  private boolean jj_2_13(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_13());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(12, xla);
    }
  }

  private boolean jj_2_14(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_14());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(13, xla);
    }
  }

  private boolean jj_2_15(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_15());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(14, xla);
    }
  }

  private boolean jj_2_16(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_16());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(15, xla);
    }
  }

  private boolean jj_2_17(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_17());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(16, xla);
    }
  }

  private boolean jj_2_18(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_18());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(17, xla);
    }
  }

  private boolean jj_2_19(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_19());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(18, xla);
    }
  }

  private boolean jj_2_20(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_20());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(19, xla);
    }
  }

  private boolean jj_2_21(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_21());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(20, xla);
    }
  }

  private boolean jj_2_22(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_22());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(21, xla);
    }
  }

  private boolean jj_2_23(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_23());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(22, xla);
    }
  }

  private boolean jj_2_24(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_24());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(23, xla);
    }
  }

  private boolean jj_2_25(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_25());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(24, xla);
    }
  }

  private boolean jj_2_26(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_26());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(25, xla);
    }
  }

  private boolean jj_2_27(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_27());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(26, xla);
    }
  }

  private boolean jj_2_28(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_28());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(27, xla);
    }
  }

  private boolean jj_2_29(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_29());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(28, xla);
    }
  }

  private boolean jj_2_30(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_30());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(29, xla);
    }
  }

  private boolean jj_2_31(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_31());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(30, xla);
    }
  }

  private boolean jj_2_32(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_32());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(31, xla);
    }
  }

  private boolean jj_2_33(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return (!jj_3_33());
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(32, xla);
    }
  }

  private boolean jj_3R_whileStatement_274_5_14() {
    if (jj_scan_token(WHILE))
      return true;
    if (jj_scan_token(ABREPARENT))
      return true;
    return false;
  }

  private boolean jj_3R_atribuicao_176_5_11() {
    if (jj_scan_token(IDENT))
      return true;
    if (jj_scan_token(ATRIBUICAO))
      return true;
    return false;
  }

  private boolean jj_3_31() {
    if (jj_scan_token(ELSE))
      return true;
    if (jj_scan_token(ABREBLOCO))
      return true;
    return false;
  }

  private boolean jj_3_26() {
    if (jj_scan_token(OPMENOR))
      return true;
    return false;
  }

  private boolean jj_3_8() {
    if (jj_3R_forStatement_293_5_15())
      return true;
    return false;
  }

  private boolean jj_3_7() {
    if (jj_3R_whileStatement_274_5_14())
      return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_3R_declaracao_186_5_10())
      return true;
    return false;
  }

  private boolean jj_3_6() {
    if (jj_3R_ifStatement_263_5_13())
      return true;
    return false;
  }

  private boolean jj_3_5() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_2()) {
      jj_scanpos = xsp;
      if (jj_3_3()) {
        jj_scanpos = xsp;
        if (jj_3_4())
          return true;
      }
    }
    if (jj_scan_token(FIMINSTRUC))
      return true;
    return false;
  }

  private boolean jj_3R_ifStatement_263_5_13() {
    if (jj_scan_token(IF))
      return true;
    if (jj_scan_token(ABREPARENT))
      return true;
    return false;
  }

  private boolean jj_3R_statement_159_5_9() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_5()) {
      jj_scanpos = xsp;
      if (jj_3_6()) {
        jj_scanpos = xsp;
        if (jj_3_7()) {
          jj_scanpos = xsp;
          if (jj_3_8())
            return true;
        }
      }
    }
    return false;
  }

  private boolean jj_3_25() {
    if (jj_scan_token(OPMAIOR))
      return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_statement_159_5_9())
      return true;
    return false;
  }

  private boolean jj_3_20() {
    if (jj_scan_token(DIVIDE))
      return true;
    return false;
  }

  private boolean jj_3_24() {
    if (jj_scan_token(ABREPARENT))
      return true;
    if (jj_3R_expression_222_5_12())
      return true;
    return false;
  }

  private boolean jj_3_23() {
    if (jj_scan_token(STRING_LITERAL))
      return true;
    return false;
  }

  private boolean jj_3_22() {
    if (jj_scan_token(IDENT))
      return true;
    return false;
  }

  private boolean jj_3R_factor_241_5_18() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_21()) {
      jj_scanpos = xsp;
      if (jj_3_22()) {
        jj_scanpos = xsp;
        if (jj_3_23()) {
          jj_scanpos = xsp;
          if (jj_3_24())
            return true;
        }
      }
    }
    return false;
  }

  private boolean jj_3_21() {
    if (jj_scan_token(NUM))
      return true;
    return false;
  }

  private boolean jj_3_17() {
    if (jj_scan_token(MINUS))
      return true;
    return false;
  }

  private boolean jj_3_19() {
    if (jj_scan_token(TIMES))
      return true;
    return false;
  }

  private boolean jj_3_18() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_19()) {
      jj_scanpos = xsp;
      if (jj_3_20())
        return true;
    }
    if (jj_3R_factor_241_5_18())
      return true;
    return false;
  }

  private boolean jj_3_11() {
    if (jj_scan_token(TIPOINT))
      return true;
    return false;
  }

  private boolean jj_3R_term_230_5_17() {
    if (jj_3R_factor_241_5_18())
      return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_18()) {
        jj_scanpos = xsp;
        break;
      }
    }
    return false;
  }

  private boolean jj_3_16() {
    if (jj_scan_token(PLUS))
      return true;
    return false;
  }

  private boolean jj_3_15() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_16()) {
      jj_scanpos = xsp;
      if (jj_3_17())
        return true;
    }
    if (jj_3R_term_230_5_17())
      return true;
    return false;
  }

  private boolean jj_3R_expression_222_5_12() {
    if (jj_3R_term_230_5_17())
      return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_15()) {
        jj_scanpos = xsp;
        break;
      }
    }
    return false;
  }

  private boolean jj_3_14() {
    if (jj_scan_token(ATRIBUICAO))
      return true;
    if (jj_3R_expression_222_5_12())
      return true;
    return false;
  }

  private boolean jj_3_33() {
    if (jj_3R_statement_159_5_9())
      return true;
    return false;
  }

  private boolean jj_3_13() {
    if (jj_scan_token(VIRGULA))
      return true;
    if (jj_3R_identifier_205_5_16())
      return true;
    return false;
  }

  private boolean jj_3_10() {
    if (jj_scan_token(TIPOFLOAT))
      return true;
    return false;
  }

  private boolean jj_3_12() {
    if (jj_scan_token(ATRIBUICAO))
      return true;
    if (jj_3R_expression_222_5_12())
      return true;
    return false;
  }

  private boolean jj_3R_identifier_205_5_16() {
    if (jj_scan_token(IDENT))
      return true;
    return false;
  }

  private boolean jj_3_28() {
    if (jj_scan_token(OPIGUAL))
      return true;
    return false;
  }

  private boolean jj_3_4() {
    if (jj_3R_expression_222_5_12())
      return true;
    return false;
  }

  private boolean jj_3R_forStatement_293_5_15() {
    if (jj_scan_token(FOR))
      return true;
    if (jj_scan_token(ABREPARENT))
      return true;
    return false;
  }

  private boolean jj_3_32() {
    if (jj_3R_statement_159_5_9())
      return true;
    return false;
  }

  private boolean jj_3_9() {
    if (jj_scan_token(TIPOCHAR))
      return true;
    return false;
  }

  private boolean jj_3R_tipoDado_196_5_19() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_9()) {
      jj_scanpos = xsp;
      if (jj_3_10()) {
        jj_scanpos = xsp;
        if (jj_3_11())
          return true;
      }
    }
    return false;
  }

  private boolean jj_3_30() {
    if (jj_3R_statement_159_5_9())
      return true;
    return false;
  }

  private boolean jj_3_27() {
    if (jj_scan_token(OPDIF))
      return true;
    return false;
  }

  private boolean jj_3_29() {
    if (jj_3R_statement_159_5_9())
      return true;
    return false;
  }

  private boolean jj_3R_declaracao_186_5_10() {
    if (jj_scan_token(INICIAVAR))
      return true;
    if (jj_3R_tipoDado_196_5_19())
      return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_3R_atribuicao_176_5_11())
      return true;
    return false;
  }

  /** Generated Token Manager. */
  public ParaCompilerTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
    jj_la1_init_0();
    jj_la1_init_1();
  }

  private static void jj_la1_init_0() {
    jj_la1_0 = new int[] {};
  }

  private static void jj_la1_init_1() {
    jj_la1_1 = new int[] {};
  }

  final private JJCalls[] jj_2_rtns = new JJCalls[33];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public ParaCompiler(java.io.InputStream stream) {
    this(stream, null);
  }

  /** Constructor with InputStream and supplied encoding */
  public ParaCompiler(java.io.InputStream stream, String encoding) {
    try {
      jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1);
    } catch (java.io.UnsupportedEncodingException e) {
      throw new RuntimeException(e);
    }
    token_source = new ParaCompilerTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < jj_2_rtns.length; i++)
      jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
    ReInit(stream, null);
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try {
      jj_input_stream.ReInit(stream, encoding, 1, 1);
    } catch (java.io.UnsupportedEncodingException e) {
      throw new RuntimeException(e);
    }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 0; i++)
      jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++)
      jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public ParaCompiler(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ParaCompilerTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < jj_2_rtns.length; i++)
      jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    if (jj_input_stream == null) {
      jj_input_stream = new SimpleCharStream(stream, 1, 1);
    } else {
      jj_input_stream.ReInit(stream, 1, 1);
    }
    if (token_source == null) {
      token_source = new ParaCompilerTokenManager(jj_input_stream);
    }

    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < jj_2_rtns.length; i++)
      jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public ParaCompiler(ParaCompilerTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < jj_2_rtns.length; i++)
      jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(ParaCompilerTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < jj_2_rtns.length; i++)
      jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null)
      token = token.next;
    else
      token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen)
              c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }

  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();

  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0;
      Token tok = token;
      while (tok != null && tok != jj_scanpos) {
        i++;
        tok = tok.next;
      }
      if (tok != null)
        jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind)
      return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos)
      throw jj_ls;
    return false;
  }

  /** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null)
      token = token.next;
    else
      token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

  /** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null)
        t = t.next;
      else
        t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk_f() {
    if ((jj_nt = token.next) == null)
      return (jj_ntk = (token.next = token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) {
      return;
    }

    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];

      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }

      for (int[] oldentry : jj_expentries) {
        if (oldentry.length == jj_expentry.length) {
          boolean isMatched = true;

          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              isMatched = false;
              break;
            }

          }
          if (isMatched) {
            jj_expentries.add(jj_expentry);
            break;
          }
        }
      }

      if (pos != 0) {
        jj_lasttokens[(jj_endpos = pos) - 1] = kind;
      }
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[37];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 0; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1 << j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1 << j)) != 0) {
            la1tokens[32 + j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 37; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

  /** Trace enabled. */
  final public boolean trace_enabled() {
    return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 33; i++) {
      try {
        JJCalls p = jj_2_rtns[i];

        do {
          if (p.gen > jj_gen) {
            jj_la = p.arg;
            jj_lastpos = jj_scanpos = p.first;
            switch (i) {
              case 0:
                jj_3_1();
                break;
              case 1:
                jj_3_2();
                break;
              case 2:
                jj_3_3();
                break;
              case 3:
                jj_3_4();
                break;
              case 4:
                jj_3_5();
                break;
              case 5:
                jj_3_6();
                break;
              case 6:
                jj_3_7();
                break;
              case 7:
                jj_3_8();
                break;
              case 8:
                jj_3_9();
                break;
              case 9:
                jj_3_10();
                break;
              case 10:
                jj_3_11();
                break;
              case 11:
                jj_3_12();
                break;
              case 12:
                jj_3_13();
                break;
              case 13:
                jj_3_14();
                break;
              case 14:
                jj_3_15();
                break;
              case 15:
                jj_3_16();
                break;
              case 16:
                jj_3_17();
                break;
              case 17:
                jj_3_18();
                break;
              case 18:
                jj_3_19();
                break;
              case 19:
                jj_3_20();
                break;
              case 20:
                jj_3_21();
                break;
              case 21:
                jj_3_22();
                break;
              case 22:
                jj_3_23();
                break;
              case 23:
                jj_3_24();
                break;
              case 24:
                jj_3_25();
                break;
              case 25:
                jj_3_26();
                break;
              case 26:
                jj_3_27();
                break;
              case 27:
                jj_3_28();
                break;
              case 28:
                jj_3_29();
                break;
              case 29:
                jj_3_30();
                break;
              case 30:
                jj_3_31();
                break;
              case 31:
                jj_3_32();
                break;
              case 32:
                jj_3_33();
                break;
            }
          }
          p = p.next;
        } while (p != null);

      } catch (LookaheadSuccess ls) {
      }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) {
        p = p.next = new JJCalls();
        break;
      }
      p = p.next;
    }

    p.gen = jj_gen + xla - jj_la;
    p.first = token;
    p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
