/* Generated By:JavaCC: Do not edit this line. ParaCompilerVisitor.java Version 4.1d1 */
package compiler;

public interface ParaCompilerVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTAtribuicao node, Object data);
  public Object visit(ASTDeclaracao node, Object data);
  public Object visit(ASTtipoDado node, Object data);
  public Object visit(ASTIdent node, Object data);
  public Object visit(ASTListaId node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTTerm node, Object data);
  public Object visit(ASTFactor node, Object data);
  public Object visit(ASTOpLog node, Object data);
  public Object visit(ASTExpLogica node, Object data);
  public Object visit(ASTIf node, Object data);
  public Object visit(ASTWhile node, Object data);
  public Object visit(ASTForInc node, Object data);
  public Object visit(ASTFor node, Object data);
}
/* JavaCC - OriginalChecksum=b43506bca92e5121efc4b4b00018f558 (do not edit this line) */
