/* ParaCompilerTokenManager.java */
/* Generated By:JJTree&JavaCC: Do not edit this line. ParaCompilerTokenManager.java */
package compiler;

import java.util.*;
import java.io.*;

/** Token Manager. */
@SuppressWarnings("unused")
public class ParaCompilerTokenManager implements ParaCompilerConstants {

   /** Debug output. */
   public java.io.PrintStream debugStream = System.out;

   /** Set debug output. */
   public void setDebugStream(java.io.PrintStream ds) {
      debugStream = ds;
   }

   private final int jjStopStringLiteralDfa_0(int pos, long active0) {
      switch (pos) {
         case 0:
            if ((active0 & 0x100000000L) != 0L)
               return 0;
            if ((active0 & 0xef880L) != 0L) {
               jjmatchedKind = 33;
               return 7;
            }
            return -1;
         case 1:
            if ((active0 & 0xef880L) != 0L) {
               jjmatchedKind = 33;
               jjmatchedPos = 1;
               return 7;
            }
            return -1;
         case 2:
            if ((active0 & 0xef880L) != 0L) {
               jjmatchedKind = 33;
               jjmatchedPos = 2;
               return 7;
            }
            return -1;
         case 3:
            if ((active0 & 0xcf080L) != 0L) {
               jjmatchedKind = 33;
               jjmatchedPos = 3;
               return 7;
            }
            if ((active0 & 0x20800L) != 0L)
               return 7;
            return -1;
         case 4:
            if ((active0 & 0xce080L) != 0L) {
               jjmatchedKind = 33;
               jjmatchedPos = 4;
               return 7;
            }
            if ((active0 & 0x1000L) != 0L)
               return 7;
            return -1;
         case 5:
            if ((active0 & 0x8a000L) != 0L) {
               jjmatchedKind = 33;
               jjmatchedPos = 5;
               return 7;
            }
            if ((active0 & 0x44080L) != 0L)
               return 7;
            return -1;
         case 6:
            if ((active0 & 0x8a000L) != 0L) {
               jjmatchedKind = 33;
               jjmatchedPos = 6;
               return 7;
            }
            return -1;
         case 7:
            if ((active0 & 0x88000L) != 0L) {
               jjmatchedKind = 33;
               jjmatchedPos = 7;
               return 7;
            }
            if ((active0 & 0x2000L) != 0L)
               return 7;
            return -1;
         case 8:
            if ((active0 & 0x80000L) != 0L) {
               jjmatchedKind = 33;
               jjmatchedPos = 8;
               return 7;
            }
            if ((active0 & 0x8000L) != 0L)
               return 7;
            return -1;
         case 9:
            if ((active0 & 0x80000L) != 0L) {
               jjmatchedKind = 33;
               jjmatchedPos = 9;
               return 7;
            }
            return -1;
         default:
            return -1;
      }
   }

   private final int jjStartNfa_0(int pos, long active0) {
      return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
   }

   private int jjStopAtPos(int pos, int kind) {
      jjmatchedKind = kind;
      jjmatchedPos = pos;
      return pos + 1;
   }

   private int jjMoveStringLiteralDfa0_0() {
      switch (curChar) {
         case 33:
            return jjMoveStringLiteralDfa1_0(0x400000L);
         case 42:
            return jjStopAtPos(0, 31);
         case 43:
            jjmatchedKind = 29;
            return jjMoveStringLiteralDfa1_0(0x1000000L);
         case 44:
            return jjStopAtPos(0, 28);
         case 45:
            jjmatchedKind = 30;
            return jjMoveStringLiteralDfa1_0(0x2010000L);
         case 46:
            return jjStopAtPos(0, 10);
         case 47:
            return jjStartNfaWithStates_0(0, 32, 0);
         case 60:
            jjmatchedKind = 8;
            return jjMoveStringLiteralDfa1_0(0x200000L);
         case 61:
            return jjMoveStringLiteralDfa1_0(0x800000L);
         case 62:
            jjmatchedKind = 9;
            return jjMoveStringLiteralDfa1_0(0x100000L);
         case 99:
            return jjMoveStringLiteralDfa1_0(0x2000L);
         case 100:
            return jjMoveStringLiteralDfa1_0(0x1800L);
         case 101:
            return jjMoveStringLiteralDfa1_0(0x24000L);
         case 105:
            return jjMoveStringLiteralDfa1_0(0x40000L);
         case 109:
            return jjMoveStringLiteralDfa1_0(0x88000L);
         case 111:
            return jjMoveStringLiteralDfa1_0(0x80L);
         case 123:
            return jjStopAtPos(0, 26);
         case 125:
            return jjStopAtPos(0, 27);
         case 160:
            return jjStopAtPos(0, 5);
         default:
            return jjMoveNfa_0(5, 0);
      }
   }

   private int jjMoveStringLiteralDfa1_0(long active0) {
      try {
         curChar = input_stream.readChar();
      } catch (java.io.IOException e) {
         jjStopStringLiteralDfa_0(0, active0);
         return 1;
      }
      switch (curChar) {
         case 43:
            if ((active0 & 0x1000000L) != 0L)
               return jjStopAtPos(1, 24);
            break;
         case 45:
            if ((active0 & 0x2000000L) != 0L)
               return jjStopAtPos(1, 25);
            break;
         case 60:
            if ((active0 & 0x200000L) != 0L)
               return jjStopAtPos(1, 21);
            break;
         case 61:
            if ((active0 & 0x400000L) != 0L)
               return jjStopAtPos(1, 22);
            else if ((active0 & 0x800000L) != 0L)
               return jjStopAtPos(1, 23);
            break;
         case 62:
            if ((active0 & 0x10000L) != 0L)
               return jjStopAtPos(1, 16);
            else if ((active0 & 0x100000L) != 0L)
               return jjStopAtPos(1, 20);
            break;
         case 97:
            return jjMoveStringLiteralDfa2_0(active0, 0xb000L);
         case 101:
            return jjMoveStringLiteralDfa2_0(active0, 0x80000L);
         case 103:
            return jjMoveStringLiteralDfa2_0(active0, 0x20000L);
         case 104:
            return jjMoveStringLiteralDfa2_0(active0, 0x80L);
         case 105:
            return jjMoveStringLiteralDfa2_0(active0, 0x800L);
         case 109:
            return jjMoveStringLiteralDfa2_0(active0, 0x4000L);
         case 110:
            return jjMoveStringLiteralDfa2_0(active0, 0x40000L);
         default:
            break;
      }
      return jjStartNfa_0(0, active0);
   }

   private int jjMoveStringLiteralDfa2_0(long old0, long active0) {
      if (((active0 &= old0)) == 0L)
         return jjStartNfa_0(0, old0);
      try {
         curChar = input_stream.readChar();
      } catch (java.io.IOException e) {
         jjStopStringLiteralDfa_0(1, active0);
         return 2;
      }
      switch (curChar) {
         case 101:
            return jjMoveStringLiteralDfa3_0(active0, 0x4000L);
         case 106:
            return jjMoveStringLiteralDfa3_0(active0, 0x80L);
         case 108:
            return jjMoveStringLiteralDfa3_0(active0, 0x1000L);
         case 113:
            return jjMoveStringLiteralDfa3_0(active0, 0x2000L);
         case 114:
            return jjMoveStringLiteralDfa3_0(active0, 0x80000L);
         case 115:
            return jjMoveStringLiteralDfa3_0(active0, 0x8800L);
         case 116:
            return jjMoveStringLiteralDfa3_0(active0, 0x40000L);
         case 117:
            return jjMoveStringLiteralDfa3_0(active0, 0x20000L);
         default:
            break;
      }
      return jjStartNfa_0(1, active0);
   }

   private int jjMoveStringLiteralDfa3_0(long old0, long active0) {
      if (((active0 &= old0)) == 0L)
         return jjStartNfa_0(1, old0);
      try {
         curChar = input_stream.readChar();
      } catch (java.io.IOException e) {
         jjStopStringLiteralDfa_0(2, active0);
         return 3;
      }
      switch (curChar) {
         case 97:
            if ((active0 & 0x20000L) != 0L)
               return jjStartNfaWithStates_0(3, 17, 7);
            return jjMoveStringLiteralDfa4_0(active0, 0x80L);
         case 101:
            return jjMoveStringLiteralDfa4_0(active0, 0x40000L);
         case 104:
            return jjMoveStringLiteralDfa4_0(active0, 0x1000L);
         case 107:
            if ((active0 & 0x800L) != 0L)
               return jjStartNfaWithStates_0(3, 11, 7);
            break;
         case 111:
            return jjMoveStringLiteralDfa4_0(active0, 0x80000L);
         case 113:
            return jjMoveStringLiteralDfa4_0(active0, 0x8000L);
         case 115:
            return jjMoveStringLiteralDfa4_0(active0, 0x4000L);
         case 117:
            return jjMoveStringLiteralDfa4_0(active0, 0x2000L);
         default:
            break;
      }
      return jjStartNfa_0(2, active0);
   }

   private int jjMoveStringLiteralDfa4_0(long old0, long active0) {
      if (((active0 &= old0)) == 0L)
         return jjStartNfa_0(2, old0);
      try {
         curChar = input_stream.readChar();
      } catch (java.io.IOException e) {
         jjStopStringLiteralDfa_0(3, active0);
         return 4;
      }
      switch (curChar) {
         case 101:
            if ((active0 & 0x1000L) != 0L)
               return jjStartNfaWithStates_0(4, 12, 7);
            break;
         case 105:
            return jjMoveStringLiteralDfa5_0(active0, 0x2000L);
         case 109:
            return jjMoveStringLiteralDfa5_0(active0, 0x4000L);
         case 114:
            return jjMoveStringLiteralDfa5_0(active0, 0x40000L);
         case 116:
            return jjMoveStringLiteralDfa5_0(active0, 0x80L);
         case 117:
            return jjMoveStringLiteralDfa5_0(active0, 0x88000L);
         default:
            break;
      }
      return jjStartNfa_0(3, active0);
   }

   private int jjMoveStringLiteralDfa5_0(long old0, long active0) {
      if (((active0 &= old0)) == 0L)
         return jjStartNfa_0(3, old0);
      try {
         curChar = input_stream.readChar();
      } catch (java.io.IOException e) {
         jjStopStringLiteralDfa_0(4, active0);
         return 5;
      }
      switch (curChar) {
         case 97:
            if ((active0 & 0x80L) != 0L)
               return jjStartNfaWithStates_0(5, 7, 7);
            else if ((active0 & 0x40000L) != 0L)
               return jjStartNfaWithStates_0(5, 18, 7);
            return jjMoveStringLiteralDfa6_0(active0, 0xa000L);
         case 98:
            return jjMoveStringLiteralDfa6_0(active0, 0x80000L);
         case 111:
            if ((active0 & 0x4000L) != 0L)
               return jjStartNfaWithStates_0(5, 14, 7);
            break;
         default:
            break;
      }
      return jjStartNfa_0(4, active0);
   }

   private int jjMoveStringLiteralDfa6_0(long old0, long active0) {
      if (((active0 &= old0)) == 0L)
         return jjStartNfa_0(4, old0);
      try {
         curChar = input_stream.readChar();
      } catch (java.io.IOException e) {
         jjStopStringLiteralDfa_0(5, active0);
         return 6;
      }
      switch (curChar) {
         case 97:
            return jjMoveStringLiteralDfa7_0(active0, 0x80000L);
         case 100:
            return jjMoveStringLiteralDfa7_0(active0, 0x2000L);
         case 110:
            return jjMoveStringLiteralDfa7_0(active0, 0x8000L);
         default:
            break;
      }
      return jjStartNfa_0(5, active0);
   }

   private int jjMoveStringLiteralDfa7_0(long old0, long active0) {
      if (((active0 &= old0)) == 0L)
         return jjStartNfa_0(5, old0);
      try {
         curChar = input_stream.readChar();
      } catch (java.io.IOException e) {
         jjStopStringLiteralDfa_0(6, active0);
         return 7;
      }
      switch (curChar) {
         case 100:
            return jjMoveStringLiteralDfa8_0(active0, 0x8000L);
         case 108:
            return jjMoveStringLiteralDfa8_0(active0, 0x80000L);
         case 111:
            if ((active0 & 0x2000L) != 0L)
               return jjStartNfaWithStates_0(7, 13, 7);
            break;
         default:
            break;
      }
      return jjStartNfa_0(6, active0);
   }

   private int jjMoveStringLiteralDfa8_0(long old0, long active0) {
      if (((active0 &= old0)) == 0L)
         return jjStartNfa_0(6, old0);
      try {
         curChar = input_stream.readChar();
      } catch (java.io.IOException e) {
         jjStopStringLiteralDfa_0(7, active0);
         return 8;
      }
      switch (curChar) {
         case 111:
            if ((active0 & 0x8000L) != 0L)
               return jjStartNfaWithStates_0(8, 15, 7);
            return jjMoveStringLiteralDfa9_0(active0, 0x80000L);
         default:
            break;
      }
      return jjStartNfa_0(7, active0);
   }

   private int jjMoveStringLiteralDfa9_0(long old0, long active0) {
      if (((active0 &= old0)) == 0L)
         return jjStartNfa_0(7, old0);
      try {
         curChar = input_stream.readChar();
      } catch (java.io.IOException e) {
         jjStopStringLiteralDfa_0(8, active0);
         return 9;
      }
      switch (curChar) {
         case 103:
            return jjMoveStringLiteralDfa10_0(active0, 0x80000L);
         default:
            break;
      }
      return jjStartNfa_0(8, active0);
   }

   private int jjMoveStringLiteralDfa10_0(long old0, long active0) {
      if (((active0 &= old0)) == 0L)
         return jjStartNfa_0(8, old0);
      try {
         curChar = input_stream.readChar();
      } catch (java.io.IOException e) {
         jjStopStringLiteralDfa_0(9, active0);
         return 10;
      }
      switch (curChar) {
         case 111:
            if ((active0 & 0x80000L) != 0L)
               return jjStartNfaWithStates_0(10, 19, 7);
            break;
         default:
            break;
      }
      return jjStartNfa_0(9, active0);
   }

   private int jjStartNfaWithStates_0(int pos, int kind, int state) {
      jjmatchedKind = kind;
      jjmatchedPos = pos;
      try {
         curChar = input_stream.readChar();
      } catch (java.io.IOException e) {
         return pos + 1;
      }
      return jjMoveNfa_0(state, pos + 1);
   }

   static final long[] jjbitVec0 = {
         0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
   };

   private int jjMoveNfa_0(int startState, int curPos) {
      int startsAt = 0;
      jjnewStateCnt = 14;
      int i = 1;
      jjstateSet[0] = startState;
      int kind = 0x7fffffff;
      for (;;) {
         if (++jjround == 0x7fffffff)
            ReInitRounds();
         if (curChar < 64) {
            long l = 1L << curChar;
            do {
               switch (jjstateSet[--i]) {
                  case 5:
                     if ((0x3ff000000000000L & l) != 0L) {
                        if (kind > 34)
                           kind = 34;
                        {
                           jjCheckNAddTwoStates(8, 9);
                        }
                     } else if (curChar == 34) {
                        jjCheckNAddTwoStates(12, 13);
                     } else if (curChar == 47)
                        jjstateSet[jjnewStateCnt++] = 0;
                     break;
                  case 0:
                     if (curChar == 47) {
                        jjCheckNAddStates(0, 2);
                     }
                     break;
                  case 1:
                     if ((0xffffffffffffdbffL & l) != 0L) {
                        jjCheckNAddStates(0, 2);
                     }
                     break;
                  case 2:
                     if ((0x2400L & l) != 0L && kind > 6)
                        kind = 6;
                     break;
                  case 3:
                     if (curChar == 10 && kind > 6)
                        kind = 6;
                     break;
                  case 4:
                     if (curChar == 13)
                        jjstateSet[jjnewStateCnt++] = 3;
                     break;
                  case 7:
                     if ((0x3ff000000000000L & l) == 0L)
                        break;
                     if (kind > 33)
                        kind = 33;
                     jjstateSet[jjnewStateCnt++] = 7;
                     break;
                  case 8:
                     if ((0x3ff000000000000L & l) == 0L)
                        break;
                     if (kind > 34)
                        kind = 34; {
                     jjCheckNAddTwoStates(8, 9);
                  }
                     break;
                  case 9:
                     if (curChar == 46) {
                        jjCheckNAdd(10);
                     }
                     break;
                  case 10:
                     if ((0x3ff000000000000L & l) == 0L)
                        break;
                     if (kind > 34)
                        kind = 34; {
                     jjCheckNAdd(10);
                  }
                     break;
                  case 11:
                     if (curChar == 34) {
                        jjCheckNAddTwoStates(12, 13);
                     }
                     break;
                  case 12:
                     if ((0xfffffffbffffffffL & l) != 0L) {
                        jjCheckNAddTwoStates(12, 13);
                     }
                     break;
                  case 13:
                     if (curChar == 34 && kind > 35)
                        kind = 35;
                     break;
                  default:
                     break;
               }
            } while (i != startsAt);
         } else if (curChar < 128) {
            long l = 1L << (curChar & 077);
            do {
               switch (jjstateSet[--i]) {
                  case 5:
                  case 7:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 33)
                        kind = 33; {
                     jjCheckNAdd(7);
                  }
                     break;
                  case 1: {
                     jjAddStates(0, 2);
                  }
                     break;
                  case 12: {
                     jjAddStates(3, 4);
                  }
                     break;
                  default:
                     break;
               }
            } while (i != startsAt);
         } else {
            int i2 = (curChar & 0xff) >> 6;
            long l2 = 1L << (curChar & 077);
            do {
               switch (jjstateSet[--i]) {
                  case 1:
                     if ((jjbitVec0[i2] & l2) != 0L) {
                        jjAddStates(0, 2);
                     }
                     break;
                  case 12:
                     if ((jjbitVec0[i2] & l2) != 0L) {
                        jjAddStates(3, 4);
                     }
                     break;
                  default:
                     break;
               }
            } while (i != startsAt);
         }
         if (kind != 0x7fffffff) {
            jjmatchedKind = kind;
            jjmatchedPos = curPos;
            kind = 0x7fffffff;
         }
         ++curPos;
         if ((i = jjnewStateCnt) == (startsAt = 14 - (jjnewStateCnt = startsAt)))
            return curPos;
         try {
            curChar = input_stream.readChar();
         } catch (java.io.IOException e) {
            return curPos;
         }
      }
   }

   /** Token literal values. */
   public static final String[] jjstrLiteralImages = {
         "", null, null, null, null, null, null, "\157\150\152\141\164\141", "\74",
         "\76", "\56", "\144\151\163\153", "\144\141\154\150\145",
         "\143\141\161\165\151\141\144\157", "\145\155\145\163\155\157", "\155\141\163\161\165\141\156\144\157",
         "\55\76",
         "\145\147\165\141", "\151\156\164\145\162\141", "\155\145\162\157\165\142\141\154\157\147\157",
         "\76\76", "\74\74", "\41\75", "\75\75", "\53\53", "\55\55", "\173", "\175", "\54",
         "\53", "\55", "\52", "\57", null, null, null, null, };

   protected Token jjFillToken() {
      final Token t;
      final String curTokenImage;
      final int beginLine;
      final int endLine;
      final int beginColumn;
      final int endColumn;
      String im = jjstrLiteralImages[jjmatchedKind];
      curTokenImage = (im == null) ? input_stream.GetImage() : im;
      beginLine = input_stream.getBeginLine();
      beginColumn = input_stream.getBeginColumn();
      endLine = input_stream.getEndLine();
      endColumn = input_stream.getEndColumn();
      t = Token.newToken(jjmatchedKind, curTokenImage);

      t.beginLine = beginLine;
      t.endLine = endLine;
      t.beginColumn = beginColumn;
      t.endColumn = endColumn;

      return t;
   }

   static final int[] jjnextStates = {
         1, 2, 4, 12, 13,
   };

   int curLexState = 0;
   int defaultLexState = 0;
   int jjnewStateCnt;
   int jjround;
   int jjmatchedPos;
   int jjmatchedKind;

   /** Get the next Token. */
   public Token getNextToken() {
      Token matchedToken;
      int curPos = 0;

      EOFLoop: for (;;) {
         try {
            curChar = input_stream.BeginToken();
         } catch (Exception e) {
            jjmatchedKind = 0;
            jjmatchedPos = -1;
            matchedToken = jjFillToken();
            return matchedToken;
         }
         image = jjimage;
         image.setLength(0);
         jjimageLen = 0;

         try {
            input_stream.backup(0);
            while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
               curChar = input_stream.BeginToken();
         } catch (java.io.IOException e1) {
            continue EOFLoop;
         }
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_0();
         if (jjmatchedKind != 0x7fffffff) {
            if (jjmatchedPos + 1 < curPos)
               input_stream.backup(curPos - jjmatchedPos - 1);
            if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L) {
               matchedToken = jjFillToken();
               TokenLexicalActions(matchedToken);
               return matchedToken;
            } else {
               continue EOFLoop;
            }
         }
         int error_line = input_stream.getEndLine();
         int error_column = input_stream.getEndColumn();
         String error_after = null;
         boolean EOFSeen = false;
         try {
            input_stream.readChar();
            input_stream.backup(1);
         } catch (java.io.IOException e1) {
            EOFSeen = true;
            error_after = curPos <= 1 ? "" : input_stream.GetImage();
            if (curChar == '\n' || curChar == '\r') {
               error_line++;
               error_column = 0;
            } else
               error_column++;
         }
         if (!EOFSeen) {
            input_stream.backup(1);
            error_after = curPos <= 1 ? "" : input_stream.GetImage();
         }
         throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, (char) curChar,
               TokenMgrError.LEXICAL_ERROR);
      }
   }

   void SkipLexicalActions(Token matchedToken) {
      switch (jjmatchedKind) {
         default:
            break;
      }
   }

   void MoreLexicalActions() {
      jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
      switch (jjmatchedKind) {
         default:
            break;
      }
   }

   void TokenLexicalActions(Token matchedToken) {
      switch (jjmatchedKind) {
         case 7:
            image.append(jjstrLiteralImages[7]);
            lengthOfMatch = jjstrLiteralImages[7].length();
            ParaCompiler.addToken("ohjata");
            break;
         case 8:
            image.append(jjstrLiteralImages[8]);
            lengthOfMatch = jjstrLiteralImages[8].length();
            ParaCompiler.addToken("<");
            break;
         case 9:
            image.append(jjstrLiteralImages[9]);
            lengthOfMatch = jjstrLiteralImages[9].length();
            ParaCompiler.addToken(">");
            break;
         case 10:
            image.append(jjstrLiteralImages[10]);
            lengthOfMatch = jjstrLiteralImages[10].length();
            ParaCompiler.addToken(".");
            break;
         case 11:
            image.append(jjstrLiteralImages[11]);
            lengthOfMatch = jjstrLiteralImages[11].length();
            ParaCompiler.addToken("disk");
            break;
         case 12:
            image.append(jjstrLiteralImages[12]);
            lengthOfMatch = jjstrLiteralImages[12].length();
            ParaCompiler.addToken("dalhe");
            break;
         case 13:
            image.append(jjstrLiteralImages[13]);
            lengthOfMatch = jjstrLiteralImages[13].length();
            ParaCompiler.addToken("caquiado");
            break;
         case 14:
            image.append(jjstrLiteralImages[14]);
            lengthOfMatch = jjstrLiteralImages[14].length();
            ParaCompiler.addToken("emesmo");
            break;
         case 15:
            image.append(jjstrLiteralImages[15]);
            lengthOfMatch = jjstrLiteralImages[15].length();
            ParaCompiler.addToken("masquando");
            break;
         case 16:
            image.append(jjstrLiteralImages[16]);
            lengthOfMatch = jjstrLiteralImages[16].length();
            ParaCompiler.addToken("->");
            break;
         case 17:
            image.append(jjstrLiteralImages[17]);
            lengthOfMatch = jjstrLiteralImages[17].length();
            ParaCompiler.addToken("egua");
            break;
         case 18:
            image.append(jjstrLiteralImages[18]);
            lengthOfMatch = jjstrLiteralImages[18].length();
            ParaCompiler.addToken("intera");
            break;
         case 19:
            image.append(jjstrLiteralImages[19]);
            lengthOfMatch = jjstrLiteralImages[19].length();
            ParaCompiler.addToken("meroubalogo");
            break;
         case 20:
            image.append(jjstrLiteralImages[20]);
            lengthOfMatch = jjstrLiteralImages[20].length();
            ParaCompiler.addToken(">>");
            break;
         case 21:
            image.append(jjstrLiteralImages[21]);
            lengthOfMatch = jjstrLiteralImages[21].length();
            ParaCompiler.addToken("<<");
            break;
         case 22:
            image.append(jjstrLiteralImages[22]);
            lengthOfMatch = jjstrLiteralImages[22].length();
            ParaCompiler.addToken("!=");
            break;
         case 23:
            image.append(jjstrLiteralImages[23]);
            lengthOfMatch = jjstrLiteralImages[23].length();
            ParaCompiler.addToken("==");
            break;
         case 24:
            image.append(jjstrLiteralImages[24]);
            lengthOfMatch = jjstrLiteralImages[24].length();
            ParaCompiler.addToken("++");
            break;
         case 25:
            image.append(jjstrLiteralImages[25]);
            lengthOfMatch = jjstrLiteralImages[25].length();
            ParaCompiler.addToken("--");
            break;
         case 26:
            image.append(jjstrLiteralImages[26]);
            lengthOfMatch = jjstrLiteralImages[26].length();
            ParaCompiler.addToken("{");
            break;
         case 27:
            image.append(jjstrLiteralImages[27]);
            lengthOfMatch = jjstrLiteralImages[27].length();
            ParaCompiler.addToken("}");
            break;
         case 28:
            image.append(jjstrLiteralImages[28]);
            lengthOfMatch = jjstrLiteralImages[28].length();
            ParaCompiler.addToken(",");
            break;
         case 29:
            image.append(jjstrLiteralImages[29]);
            lengthOfMatch = jjstrLiteralImages[29].length();
            ParaCompiler.addToken("+");
            break;
         case 30:
            image.append(jjstrLiteralImages[30]);
            lengthOfMatch = jjstrLiteralImages[30].length();
            ParaCompiler.addToken("-");
            break;
         case 31:
            image.append(jjstrLiteralImages[31]);
            lengthOfMatch = jjstrLiteralImages[31].length();
            ParaCompiler.addToken("*");
            break;
         case 32:
            image.append(jjstrLiteralImages[32]);
            lengthOfMatch = jjstrLiteralImages[32].length();
            ParaCompiler.addToken("/");
            break;
         case 33:
            image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
            ParaCompiler.addToken("IDENT:" + image);
            break;
         case 34:
            image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
            ParaCompiler.addToken("NUM:" + image);
            break;
         case 35:
            image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
            ParaCompiler.addToken("STRING:" + image);
            break;
         default:
            break;
      }
   }

   private void jjCheckNAdd(int state) {
      if (jjrounds[state] != jjround) {
         jjstateSet[jjnewStateCnt++] = state;
         jjrounds[state] = jjround;
      }
   }

   private void jjAddStates(int start, int end) {
      do {
         jjstateSet[jjnewStateCnt++] = jjnextStates[start];
      } while (start++ != end);
   }

   private void jjCheckNAddTwoStates(int state1, int state2) {
      jjCheckNAdd(state1);
      jjCheckNAdd(state2);
   }

   private void jjCheckNAddStates(int start, int end) {
      do {
         jjCheckNAdd(jjnextStates[start]);
      } while (start++ != end);
   }

   /** Constructor. */
   public ParaCompilerTokenManager(SimpleCharStream stream) {

      if (SimpleCharStream.staticFlag)
         throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

      input_stream = stream;
   }

   /** Constructor. */
   public ParaCompilerTokenManager(SimpleCharStream stream, int lexState) {
      ReInit(stream);
      SwitchTo(lexState);
   }

   /** Reinitialise parser. */

   public void ReInit(SimpleCharStream stream) {

      jjmatchedPos = jjnewStateCnt = 0;
      curLexState = defaultLexState;
      input_stream = stream;
      ReInitRounds();
   }

   private void ReInitRounds() {
      int i;
      jjround = 0x80000001;
      for (i = 14; i-- > 0;)
         jjrounds[i] = 0x80000000;
   }

   /** Reinitialise parser. */
   public void ReInit(SimpleCharStream stream, int lexState)

   {
      ReInit(stream);
      SwitchTo(lexState);
   }

   /** Switch to specified lex state. */
   public void SwitchTo(int lexState) {
      if (lexState >= 1 || lexState < 0)
         throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.",
               TokenMgrError.INVALID_LEXICAL_STATE);
      else
         curLexState = lexState;
   }

   /** Lexer state names. */
   public static final String[] lexStateNames = {
         "DEFAULT",
   };

   /** Lex State array. */
   public static final int[] jjnewLexState = {
         -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
         -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
   };
   static final long[] jjtoToken = {
         0xfffffff81L,
   };
   static final long[] jjtoSkip = {
         0x7eL,
   };
   static final long[] jjtoSpecial = {
         0x0L,
   };
   static final long[] jjtoMore = {
         0x0L,
   };
   protected SimpleCharStream input_stream;

   private final int[] jjrounds = new int[14];
   private final int[] jjstateSet = new int[2 * 14];
   private final StringBuilder jjimage = new StringBuilder();
   private StringBuilder image = jjimage;
   private int jjimageLen;
   private int lengthOfMatch;
   protected int curChar;
}
