/* Generated By:JavaCC: Do not edit this line. ParaCompilerDefaultVisitor.java Version 7.0.12 */
package compiler;

public class ParaCompilerDefaultVisitor implements ParaCompilerVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTProgram node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAtribuicao node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDeclaracao node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTtipoDado node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIdent node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTListaId node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTerm node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFactor node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOpLog node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExpLogica node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIf node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTWhile node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTForInc node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFor node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=e0e20b98352a76ed68ba608e5a16c597 (do not edit this line) */
